import {
  faClock,
  faQuestionCircle,
  faSearch,
  faTimes,
  faComments,
  faClone,
  faListAlt,
  faUserFriends,
  faSmile,
  faGrinSquint,
  faLaugh,
  faComment,
  faEllipsisV,
  faStar,
  faUserPlus,
  faLock,
  faHashtag,
  faInfo,
  faPaperPlane,
} from '@fortawesome/free-solid-svg-icons'

const myIcon = {
  clock: faClock,
  question: faQuestionCircle,
  search: faSearch,
  close: faTimes,
  message: faComments,
  file: faClone,
  channels: faListAlt,
  people: faUserFriends,
  smile: faSmile,
  toggleSmile: faGrinSquint,
  laughEmoji: faLaugh,
  comment: faComment,
  ellipsis: faEllipsisV,
  star: faStar,
  addUser: faUserPlus,
  lock: faLock,
  hashtag: faHashtag,
  info: faInfo,
  paperPlane: faPaperPlane,
}

export default myIcon
