import {
  faClock,
  faQuestionCircle,
  faSearch,
  faTimes,
  faComments,
  faClone,
  faListAlt,
  faUserFriends,
  faSmile,
  faGrinSquint,
  faLaugh,
  faComment,
  faEllipsisV,
  faEdit,
  faCommentDots,
  faAt,
  faChevronRight,
  faChevronDown,
  faHashtag,
  faLock,
} from '@fortawesome/free-solid-svg-icons'

const myIcon = {
  clock: faClock,
  question: faQuestionCircle,
  search: faSearch,
  close: faTimes,
  message: faComments,
  file: faClone,
  channels: faListAlt,
  people: faUserFriends,
  smile: faSmile,
  toggleSmile: faGrinSquint,
  laughEmoji: faLaugh,
  comment: faComment,
  ellipsis: faEllipsisV,
  edit: faEdit,
  thread: faCommentDots,
  at: faAt,
  right: faChevronRight,
  down: faChevronDown,
  public: faHashtag,
  private: faLock,
}

export default myIcon
