import {
  faClock,
  faQuestionCircle,
  faSearch,
  faTimes,
  faComments,
  faClone,
  faListAlt,
  faUserFriends,
  faSmile,
  faGrinSquint,
  faLaugh,
  faComment,
  faEllipsisV,
  faEdit,
  faCommentDots,
  faAt,
  faChevronRight,
  faChevronDown,
  faHashtag,
  faLock,
  faTrashAlt,
  faCircle,
  faStar,
  faUserPlus,
  faInfo,
  faPlus,
  faPaperPlane,
  faPaperclip,
  faCheck,
  faArrowRight,
} from '@fortawesome/free-solid-svg-icons'

const myIcon = {
  clock: faClock,
  question: faQuestionCircle,
  search: faSearch,
  close: faTimes,
  message: faComments,
  file: faClone,
  channels: faListAlt,
  people: faUserFriends,
  smile: faSmile,
  toggleSmile: faGrinSquint,
  laughEmoji: faLaugh,
  comment: faComment,
  ellipsis: faEllipsisV,
  edit: faEdit,
  thread: faCommentDots,
  at: faAt,
  right: faChevronRight,
  down: faChevronDown,
  trashAlt: faTrashAlt,
  online: faCircle,
  star: faStar,
  addUser: faUserPlus,
  lock: faLock,
  hashtag: faHashtag,
  info: faInfo,
  plus: faPlus,
  paperPlane: faPaperPlane,
  paperClip: faPaperclip,
  check: faCheck,
  rightArrow: faArrowRight,
}

export default myIcon
